name: audiobible
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_tts:
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/Bible/1 Chronicles.txt
    - assets/Bible/1 Corinthians.txt
    - assets/Bible/1 John.txt
    - assets/Bible/1 Kings.txt
    - assets/Bible/1 Peter.txt
    - assets/Bible/1 Samuel.txt
    - assets/Bible/1 Thessalonians.txt
    - assets/Bible/1 Timothy.txt
    - assets/Bible/2 Chronicles.txt
    - assets/Bible/2 Corinthians.txt
    - assets/Bible/2 John.txt
    - assets/Bible/2 Kings.txt
    - assets/Bible/2 Peter.txt
    - assets/Bible/2 Samuel.txt
    - assets/Bible/2 Thessalonians.txt
    - assets/Bible/2 Timothy.txt
    - assets/Bible/3 John.txt
    - assets/Bible/Acts.txt
    - assets/Bible/Amos.txt
    - assets/Bible/bible.txt
    - assets/Bible/Colossians.txt
    - assets/Bible/Daniel.txt
    - assets/Bible/Deuteronomy.txt
    - assets/Bible/Ecclesiastes.txt
    - assets/Bible/Ephesians.txt
    - assets/Bible/Esther.txt
    - assets/Bible/Exodus.txt
    - assets/Bible/Ezekiel.txt
    - assets/Bible/Ezra.txt
    - assets/Bible/Galatians.txt
    - assets/Bible/Genesis.txt
    - assets/Bible/Habakkuk.txt
    - assets/Bible/Haggai.txt
    - assets/Bible/Hebrews.txt
    - assets/Bible/Hosea.txt
    - assets/Bible/Isaiah.txt
    - assets/Bible/James.txt
    - assets/Bible/Jeremiah.txt
    - assets/Bible/Job.txt
    - assets/Bible/Joel.txt
    - assets/Bible/John.txt
    - assets/Bible/Jonah.txt
    - assets/Bible/Joshua.txt
    - assets/Bible/Jude.txt
    - assets/Bible/Judges.txt
    - assets/Bible/Lamentations.txt
    - assets/Bible/Leviticus.txt
    - assets/Bible/Luke.txt
    - assets/Bible/Malachi.txt
    - assets/Bible/Mark.txt
    - assets/Bible/Mattew.txt
    - assets/Bible/Matther.txt
    - assets/Bible/Matthew.txt
    - assets/Bible/Micah.txt
    - assets/Bible/Nahum.txt
    - assets/Bible/Nehemiah.txt
    - assets/Bible/Numbers.txt
    - assets/Bible/Obadiah.txt
    - assets/Bible/Philemon.txt
    - assets/Bible/Philippians.txt
    - assets/Bible/Proverbs.txt
    - assets/Bible/Psalm.txt
    - assets/Bible/Revelation.txt
    - assets/Bible/Romans.txt
    - assets/Bible/Ruth.txt
    - assets/Bible/Song of Solomon.txt
    - assets/Bible/Titus.txt
    - assets/Bible/Zechariah.txt
    - assets/Bible/Zephaniah.txt
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
